local button = CreateFrame('Button', 'AutoAttackForeverMinimapButton', Minimap)
button:SetSize(32, 32)
button:SetFrameLevel(Minimap:GetFrameLevel() + 5)
button:RegisterForClicks('LeftButtonUp', 'RightButtonUp')
button:RegisterForDrag('LeftButton')
button:SetHighlightTexture('Interface\\Minimap\\UI-Minimap-ZoomButton-Highlight')
local icon = button:CreateTexture(nil, 'BACKGROUND')
icon:SetSize(24, 24)
icon:SetPoint('CENTER', 0, 1)
icon:SetTexture('Interface\\AddOns\\AdaptiveAutoAttack\\Art\\AAFLogo')
local border = button:CreateTexture(nil, 'OVERLAY')
border:SetSize(54, 54)
border:SetPoint('TOPLEFT')
border:SetTexture('Interface\\Minimap\\MiniMap-TrackingBorder')
local function position(angle)
    local radians = math.rad(angle)
    local radius = Minimap:GetWidth() / 2 + 8
    button:ClearAllPoints()
    button:SetPoint('CENTER', Minimap, 'CENTER', math.cos(radians) * radius, math.sin(radians) * radius)
end
button:SetScript('OnClick', function()
    if not button.dragging then InterfaceOptionsFrame_OpenToCategory(AutoAttackForeverOptions) end
end)
button:SetScript('OnEnter', function(self)
    GameTooltip:SetOwner(self, 'ANCHOR_LEFT')
    GameTooltip:SetText('Auto-Attack Forever')
    GameTooltip:AddLine('Click to open settings.', 1, 1, 1)
    GameTooltip:AddLine('Drag to move around the minimap.', 1, 1, 1)
    GameTooltip:Show()
end)
button:SetScript('OnLeave', function() GameTooltip:Hide() end)
button:SetScript('OnDragStart', function(self)
    self.dragging = true
    GameTooltip:Hide()
    self:SetScript('OnUpdate', function()
        local x, y = GetCursorPosition()
        local scale = Minimap:GetEffectiveScale()
        local cx, cy = Minimap:GetCenter()
        local angle = math.deg(math.atan2(y / scale - cy, x / scale - cx))
        AAFMinimapDB.angle = angle
        position(angle)
    end)
end)
button:SetScript('OnDragStop', function(self)
    self:SetScript('OnUpdate', nil)
    self.dragging = nil
end)
button:RegisterEvent('ADDON_LOADED')
button:SetScript('OnEvent', function(self, _, name)
    if name ~= 'AdaptiveAutoAttack' then return end
    if type(AAFMinimapDB) ~= 'table' then AAFMinimapDB = {} end
    if type(AAFMinimapDB.angle) ~= 'number' then AAFMinimapDB.angle = 225 end
    position(AAFMinimapDB.angle)
    self:UnregisterEvent('ADDON_LOADED')
end)
